"""
tests/test_pdf_parser.py
-------------------------
End-to-end tests for src/parser/pdf_parser.py using the sample PDF
generated by tests/create_test_pdf.py.
"""

from pathlib import Path

import pandas as pd
import pytest

SAMPLE_PDF = Path("tests/sample_pdfs/TechMahindra_IEPF_2017-2018.pdf")

# Skip all tests in this module if the sample PDF hasn't been generated yet
pytestmark = pytest.mark.skipif(
    not SAMPLE_PDF.exists(),
    reason=(
        "Sample PDF not found. Run: python tests/create_test_pdf.py "
        "to generate it first."
    ),
)

REQUIRED_COLUMNS = [
    "folio_no", "name", "address", "demat_account", "pan_number",
    "current_holding", "total_dividend", "company_name",
    "source_file", "year", "parsed_at",
]


class TestParsePdf:
    def test_returns_dataframe(self, tmp_path: Path):
        from src.parser.pdf_parser import parse_pdf
        df = parse_pdf(str(SAMPLE_PDF), output_dir=str(tmp_path), skip_excel_write=True)
        assert isinstance(df, pd.DataFrame)

    def test_extracts_records(self, tmp_path: Path):
        from src.parser.pdf_parser import parse_pdf
        df = parse_pdf(str(SAMPLE_PDF), output_dir=str(tmp_path), skip_excel_write=True)
        assert len(df) > 0, "Expected at least 1 record from sample PDF"

    def test_required_columns_present(self, tmp_path: Path):
        from src.parser.pdf_parser import parse_pdf
        df = parse_pdf(str(SAMPLE_PDF), output_dir=str(tmp_path), skip_excel_write=True)
        if df.empty:
            pytest.skip("No records extracted — extractor may need adjustment.")
        for col in REQUIRED_COLUMNS:
            assert col in df.columns, f"Missing column: {col}"

    def test_total_dividend_positive(self, tmp_path: Path):
        from src.parser.pdf_parser import parse_pdf
        df = parse_pdf(str(SAMPLE_PDF), output_dir=str(tmp_path), skip_excel_write=True)
        if df.empty or "total_dividend" not in df.columns:
            pytest.skip("No dividend data extracted.")
        assert df["total_dividend"].sum() > 0

    def test_excel_file_created(self, tmp_path: Path):
        """When skip_excel_write=False, an Excel file should be created."""
        from src.parser.pdf_parser import parse_pdf
        master = tmp_path / "master.xlsx"
        df = parse_pdf(
            str(SAMPLE_PDF),
            output_dir=str(tmp_path / "parsed"),
            master_path=str(master),
            skip_excel_write=False,
        )
        if df.empty:
            pytest.skip("No records extracted.")
        xlsx_files = list((tmp_path / "parsed").rglob("*.xlsx"))
        assert len(xlsx_files) >= 1, "Expected at least one individual Excel file"

    def test_nonexistent_pdf_returns_empty(self, tmp_path: Path):
        from src.parser.pdf_parser import parse_pdf
        df = parse_pdf(
            "nonexistent_file.pdf",
            output_dir=str(tmp_path),
            skip_excel_write=True,
        )
        assert df.empty


class TestParseAllPdfs:
    def test_folder_mode_returns_dataframe(self, tmp_path: Path):
        from src.parser.pdf_parser import parse_all_pdfs
        df = parse_all_pdfs(
            str(SAMPLE_PDF.parent),
            output_dir=str(tmp_path / "parsed"),
            master_path=str(tmp_path / "master.xlsx"),
        )
        assert isinstance(df, pd.DataFrame)

    def test_empty_folder_returns_empty(self, tmp_path: Path):
        from src.parser.pdf_parser import parse_all_pdfs
        df = parse_all_pdfs(str(tmp_path))
        assert df.empty

    def test_nonexistent_folder_returns_empty(self):
        from src.parser.pdf_parser import parse_all_pdfs
        df = parse_all_pdfs("/nonexistent/folder/path/")
        assert df.empty


class TestAddressContinuationMerge:
    def test_continuation_rows_merged(self):
        from src.parser.pdf_parser import _merge_address_continuations

        df = pd.DataFrame({
            "folio_no": ["TM001", "", "TM002"],
            "name":     ["Rajesh", "", "Priya"],
            "address":  ["123 Main St", "Mumbai 400001", "456 Park Ave"],
        })
        result = _merge_address_continuations(df)
        # The continuation row ("" folio) should be merged into TM001
        assert len(result) == 2
        assert "Mumbai 400001" in result.iloc[0]["address"]

    def test_no_continuation_unchanged(self):
        from src.parser.pdf_parser import _merge_address_continuations

        df = pd.DataFrame({
            "folio_no": ["TM001", "TM002"],
            "name":     ["Rajesh", "Priya"],
            "address":  ["123 Main", "456 Park"],
        })
        result = _merge_address_continuations(df)
        assert len(result) == 2
